In [1]:
import pandas as pd

In [6]:
df=pd.read_csv("Dataset-1.csv")
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0

In [7]:
df.head(10)

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0
5,6,Sneha,22.0,Female,Delhi,25000.0,HR,15/02/2024,1.234500e+04,1.0
6,7,Rahul,18.0,Female,Delhi,35000.0,Sales,Mar 10 2024,NaN,3.0
7,8,Rahul,NaN,M,Bhopal,35000.0,HR,Mar 10 2024,1.000000e+10,NaN
8,9,Rahul,22.0,NaN,Bhopal,35000.0,HR,NaN,NaN,NaN
9,10,Rahul,NaN,Female,Delhi,NaN,Finance,NaN,9.876543e+09,4.0

In [8]:
df.shape

(5000, 10)

In [9]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Department',
       'Join_Date', 'Phone', 'Performance_Score'],
      dtype='object')

In [10]:
df.dtypes

Customer_ID            int64
Name                  object
Age                  float64
Gender                object
City                  object
Salary               float64
Department            object
Join_Date             object
Phone                float64
Performance_Score    float64
dtype: object

In [11]:
df.describe()

       Customer_ID          Age        Salary         Phone  Performance_Score
count  5000.000000  4436.000000   4126.000000  3.735000e+03        4161.000000
mean   2500.500000    39.494364  31994.183228  6.632526e+09           2.996155
std    1443.520003    44.259140  19329.449100  4.682321e+09           1.428247
min       1.000000    -5.000000  -1000.000000  1.234500e+04           1.000000
25%    1250.750000    18.000000  25000.000000  1.234500e+04           2.000000
50%    2500.500000    25.000000  35000.000000  9.876543e+09           3.000000
75%    3750.250000    35.000000  45000.000000  1.000000e+10           4.000000
max    5000.000000   150.000000  55000.000000  1.000000e+10           5.000000

In [12]:
df.describe(include="object")

         Name Gender    City Department   Join_Date
count    5000   3969    4280       3967        3705
unique      8      4       6          4           3
top     Rahul   Male  Mumbai      Sales  15/02/2024
freq      643   1005     759       1019        1265

In [17]:
df["Gender"].value_counts()

Gender
Male      1005
M         1002
Female    1000
F          962
Name: count, dtype: int64

In [13]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                   564
Gender               1031
City                  720
Salary                874
Department           1033
Join_Date            1295
Phone                1265
Performance_Score     839
dtype: int64

In [14]:
df.isnull().sum().sum()

7621

In [15]:
df.duplicated().sum()

0

In [16]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_8992\2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [17]:
df["City"].fillna("Delhi",inplace=True)

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_8992\158026011.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna("Delhi",inplace=True)

In [18]:
df["Join_Date"]=df["Join_Date"].fillna (method="ffill")

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_8992\1317153760.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Join_Date"]=df["Join_Date"].fillna (method="ffill")

In [19]:
df.isnull().sum()

Customer_ID             0
Name                    0
Age                     0
Gender               1031
City                    0
Salary                874
Department           1033
Join_Date               0
Phone                1265
Performance_Score     839
dtype: int64

In [20]:
df.loc[0]

Customer_ID                     1
Name                        Pooja
Age                          18.0
Gender                          M
City                         Pune
Salary                    25000.0
Department                     HR
Join_Date             Mar 10 2024
Phone                9876543210.0
Performance_Score             1.0
Name: 0, dtype: object

In [21]:
df.loc[0:5,"City"]

0         Pune
1       Bhopal
2       Bhopal
3       Mumbai
4        Delhi
5      Delhi
Name: City, dtype: object

In [22]:
df.loc[0:5,"Name"]

0    Pooja
1    Pooja
2    Priya
3    Sneha
4    Pooja
5    Sneha
Name: Name, dtype: object

In [23]:
df.iloc[0:5,2]

0    18.0
1    40.0
2    18.0
3    30.0
4    22.0
Name: Age, dtype: float64

In [24]:
df.iloc[0:5,0:2]

   Customer_ID   Name
0            1  Pooja
1            2  Pooja
2            3  Priya
3            4  Sneha
4            5  Pooja

In [53]:
df.duplicated(subset=["Name"]).sum()

4992

In [25]:
df.dropna()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,Delhi,55000.0,IT,Mar 10 2024,1.234500e+04,1.0
5,6,Sneha,22.0,Female,Delhi,25000.0,HR,15/02/2024,1.234500e+04,1.0
10,11,Anjali,22.0,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,4.0
...,...,...,...,...,...,...,...,...,...,...
4977,4978,Pooja,40.0,Female,Bhopal,35000.0,Finance,15/02/2024,1.000000e+10,3.0
4981,4982,Priya,22.0,F,Bhopal,55000.0,HR,Mar 10 2024,1.000000e+10,5.0
4992,4993,Anjali,150.0,Male,Pune,45000.0,Sales,2024-01-15,1.000000e+10,3.0
4993,4994,Rahul,18.0,Female,Bhopal,25000.0,Sales,Mar 10 2024,1.000000e+10,5.0
4998,4999,Vikas,150.0,Male,Mumbai,-1000.0,HR,Mar 10 2024,1.000000e+10,1.0

In [26]:
import pandas as pd
import numpy as np

In [27]:
print(df.isnull().sum().sum())

5042

In [28]:
print(df.columns[df.isnull().any()])

Index(['Gender', 'Salary', 'Department', 'Phone', 'Performance_Score'], dtype='object')

In [29]:
print((df.isnull().sum()/len(df))*100)

Customer_ID           0.00
Name                  0.00
Age                   0.00
Gender               20.62
City                  0.00
Salary               17.48
Department           20.66
Join_Date             0.00
Phone                25.30
Performance_Score    16.78
dtype: float64

In [30]:
print(df.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [31]:
print(df[df.duplicated()])

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [32]:
df=df.drop_duplicates()

In [33]:
print(df[df['Customer_ID'].duplicated()])

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [34]:
print(df[df['Age']<0])

      Customer_ID    Name  Age  Gender       City   Salary Department  \
13             14   Rahul -5.0    Male  Bengaluru  55000.0         IT
23             24  Anjali -5.0       F  Bengaluru  -1000.0        NaN
25             26   Sneha -5.0    Male  Bengaluru  -1000.0         IT
33             34   Sneha -5.0  Female      Delhi  25000.0         IT
43             44   Rohit -5.0  Female  Bengaluru  25000.0         IT
...           ...     ...  ...     ...        ...      ...        ...
4965         4966   Priya -5.0     NaN     Mumbai  55000.0    Finance
4971         4972   Rahul -5.0       M     Bhopal  25000.0    Finance
4972         4973  Anjali -5.0    Male      Delhi  45000.0        NaN
4976         4977   Vikas -5.0    Male      Delhi      NaN         HR
4980         4981   Rahul -5.0       M      Delhi  35000.0         HR

        Join_Date         Phone  Performance_Score
13    Mar 10 2024  9.876543e+09                3.0
23     15/02/2024           NaN                5.0
25     15/02/2024  9.876543e+09                5.0
33     2024-01-15  9.876543e+09                3.0
43     2024-01-15  1.234500e+04                3.0
...           ...           ...                ...
4965   15/02/2024  1.000000e+10                4.0
4971   15/02/2024  1.000000e+10                4.0
4972   15/02/2024  1.000000e+10                1.0
4976   2024-01-15  1.234500e+04                3.0
4980   2024-01-15  1.000000e+10                NaN

[563 rows x 10 columns]

In [35]:
print(df[df['Age']>100])

      Customer_ID    Name    Age  Gender       City   Salary Department  \
24             25   Priya  150.0    Male       Pune  25000.0      Sales
31             32   Sneha  150.0  Female     Bhopal  35000.0         IT
39             40  Anjali  150.0    Male    Delhi        NaN        NaN
42             43  Anjali  150.0       F      Delhi  -1000.0         IT
51             52   Vikas  150.0  Female      Delhi  55000.0        NaN
...           ...     ...    ...     ...        ...      ...        ...
4970         4971   Priya  150.0     NaN    Delhi    55000.0      Sales
4973         4974    Amit  150.0       M  Bengaluru      NaN    Finance
4992         4993  Anjali  150.0    Male       Pune  45000.0      Sales
4996         4997   Priya  150.0     NaN    Delhi    -1000.0         IT
4998         4999   Vikas  150.0    Male     Mumbai  -1000.0         HR

        Join_Date         Phone  Performance_Score
24     15/02/2024  1.234500e+04                5.0
31    Mar 10 2024           NaN                5.0
39    Mar 10 2024  1.000000e+10                2.0
42     2024-01-15  1.000000e+10                2.0
51     2024-01-15           NaN                1.0
...           ...           ...                ...
4970   2024-01-15  1.234500e+04                3.0
4973  Mar 10 2024  1.000000e+10                5.0
4992   2024-01-15  1.000000e+10                3.0
4996  Mar 10 2024  1.234500e+04                4.0
4998  Mar 10 2024  1.000000e+10                1.0

[569 rows x 10 columns]

In [36]:
df.loc[(df['Age']<0) | (df['Age']>100),'Age']=np.nan
df['Age'].fillna(df['Age'].median(),inplace=True)

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_8992\49254859.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace=True)

In [37]:
print(df[df['Salary']<0])

      Customer_ID    Name        Age  Gender       City  Salary Department  \
1               2   Pooja  40.000000  Female     Bhopal -1000.0        NaN
3               4   Sneha  30.000000  Female     Mumbai -1000.0      Sales
18             19   Priya  39.494364    Male      Delhi -1000.0    Finance
23             24  Anjali  30.000000       F  Bengaluru -1000.0        NaN
25             26   Sneha  30.000000    Male  Bengaluru -1000.0         IT
...           ...     ...        ...     ...        ...     ...        ...
4987         4988   Rahul  35.000000       M  Bengaluru -1000.0         IT
4991         4992   Rahul  22.000000     NaN     Bhopal -1000.0         IT
4994         4995   Sneha  40.000000       M     Bhopal -1000.0    Finance
4996         4997   Priya  30.000000     NaN    Delhi   -1000.0         IT
4998         4999   Vikas  30.000000    Male     Mumbai -1000.0         HR

        Join_Date         Phone  Performance_Score
1     Mar 10 2024  1.234500e+04                2.0
3     Mar 10 2024  9.876543e+09                5.0
18     2024-01-15  1.000000e+10                4.0
23     15/02/2024           NaN                5.0
25     15/02/2024  9.876543e+09                5.0
...           ...           ...                ...
4987  Mar 10 2024           NaN                1.0
4991   2024-01-15  9.876543e+09                5.0
4994   2024-01-15           NaN                3.0
4996  Mar 10 2024  1.234500e+04                4.0
4998  Mar 10 2024  1.000000e+10                1.0

[827 rows x 10 columns]

In [75]:
df.loc[(df['Salary']<0) | (df['Salary']>100),'Salary']=np.nan
df['Salary'].fillna(df['Salary'].median(),inplace=True)

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_13468\4119292698.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace=True)

In [38]:
import pandas as pd
import numpy as np
df=pd.read_csv("Dataset-1.csv")
df.head()
df['Salary'].fillna(df['Salary'].median(),inplace=True)

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_8992\2253971259.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace=True)

In [39]:
print(df['Gender'].unique())

['M' 'Female' 'F' nan 'Male']

In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv("Dataset-1.csv")
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0

In [5]:
df['Gender']=df['Gender'].replace(['M','male'],'Male')

In [6]:
df['Gender']=df['Gender'].replace(['F','female'],'Female')

In [8]:
print(df[df['Gender'].isnull()])

      Customer_ID   Name    Age Gender       City   Salary Department  \
8               9  Rahul   22.0    NaN     Bhopal  35000.0         HR
21             22  Priya   35.0    NaN      Delhi  35000.0    Finance
32             33   Amit   35.0    NaN     Bhopal  -1000.0        NaN
35             36  Priya   40.0    NaN        NaN  25000.0         HR
40             41  Priya   30.0    NaN    Delhi    55000.0         HR
...           ...    ...    ...    ...        ...      ...        ...
4984         4985  Pooja   35.0    NaN       Pune      NaN         IT
4985         4986  Rohit   35.0    NaN     Bhopal  35000.0         HR
4991         4992  Rahul   22.0    NaN     Bhopal  -1000.0         IT
4995         4996  Rahul   18.0    NaN      Delhi  55000.0    Finance
4996         4997  Priya  150.0    NaN    Delhi    -1000.0         IT

        Join_Date         Phone  Performance_Score
8             NaN           NaN                NaN
21     2024-01-15  1.000000e+10                NaN
32     2024-01-15           NaN                5.0
35     2024-01-15  1.000000e+10                NaN
40            NaN           NaN                2.0
...           ...           ...                ...
4984  Mar 10 2024           NaN                NaN
4985          NaN           NaN                5.0
4991   2024-01-15  9.876543e+09                5.0
4995  Mar 10 2024           NaN                NaN
4996  Mar 10 2024  1.234500e+04                4.0

[1031 rows x 10 columns]

In [9]:
print(df['City'].unique())

['Pune' 'Bhopal' 'Mumbai' nan '  Delhi  ' 'Delhi' 'Bengaluru']

In [10]:
df['City']=df['City'].str.strip()

In [11]:
df['City']=df['City'].str.title()

In [12]:
print(df[df['City'].isnull()])

      Customer_ID    Name    Age  Gender City   Salary Department  \
4               5   Pooja   22.0    Male  NaN  55000.0         IT
12             13    Amit   30.0    Male  NaN      NaN    Finance
18             19   Priya    NaN    Male  NaN  -1000.0    Finance
35             36   Priya   40.0     NaN  NaN  25000.0         HR
38             39   Pooja   25.0    Male  NaN  -1000.0    Finance
...           ...     ...    ...     ...  ...      ...        ...
4962         4963   Vikas  150.0    Male  NaN  25000.0    Finance
4964         4965   Sneha   18.0  Female  NaN  25000.0      Sales
4969         4970   Rohit  150.0    Male  NaN  55000.0        NaN
4972         4973  Anjali   -5.0    Male  NaN  45000.0        NaN
4976         4977   Vikas   -5.0    Male  NaN      NaN         HR

        Join_Date         Phone  Performance_Score
4     Mar 10 2024  1.234500e+04                1.0
12     2024-01-15           NaN                NaN
18     2024-01-15  1.000000e+10                4.0
35     2024-01-15  1.000000e+10                NaN
38            NaN  9.876543e+09                2.0
...           ...           ...                ...
4962  Mar 10 2024  1.000000e+10                NaN
4964   15/02/2024  1.000000e+10                2.0
4969   15/02/2024  9.876543e+09                NaN
4972          NaN  1.000000e+10                1.0
4976          NaN  1.234500e+04                3.0

[720 rows x 10 columns]

In [13]:
print(df.dtypes)

Customer_ID            int64
Name                  object
Age                  float64
Gender                object
City                  object
Salary               float64
Department            object
Join_Date             object
Phone                float64
Performance_Score    float64
dtype: object

In [15]:
print(df[df['Join_date'].isnull()])

      Customer_ID    Name    Age  Gender    City   Salary Department  \
1               2   Pooja   40.0  Female  Bhopal  -1000.0        NaN
2               3   Priya   18.0  Female  Bhopal      NaN         IT
5               6   Sneha   22.0  Female   Delhi  25000.0         HR
8               9   Rahul   22.0     NaN  Bhopal  35000.0         HR
9              10   Rahul    NaN  Female   Delhi      NaN    Finance
...           ...     ...    ...     ...     ...      ...        ...
4992         4993  Anjali  150.0    Male    Pune  45000.0      Sales
4994         4995   Sneha   40.0    Male  Bhopal  -1000.0    Finance
4997         4998   Rohit   22.0  Female   Delhi  35000.0         HR
4998         4999   Vikas  150.0    Male  Mumbai  -1000.0         HR
4999         5000  Anjali   30.0  Female   Delhi  45000.0      Sales

       Join_Date         Phone  Performance_Score Join_date
1            NaN  1.234500e+04                2.0       NaT
2     15/02/2024           NaN                4.0       NaT
5     15/02/2024  1.234500e+04                1.0       NaT
8            NaN           NaN                NaN       NaT
9            NaN  9.876543e+09                4.0       NaT
...          ...           ...                ...       ...
4992  2024-01-15  1.000000e+10                3.0       NaT
4994  2024-01-15           NaN                3.0       NaT
4997         NaN           NaN                5.0       NaT
4998         NaN  1.000000e+10                1.0       NaT
4999         NaN           NaN                3.0       NaT

[3777 rows x 11 columns]

In [21]:
df['Month']=df['Join_Date'.dt.month]

AttributeError: 'str' object has no attribute 'dt'

In [22]:
import pandas as pd
df['Join_date']=pd.to_datetime(df['Join_Date'],errors='coerce')
print(df['Join_Date'].dtype)

object

In [24]:
print(df.columns)

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'City', 'Salary', 'Department',
       'Join_Date', 'Phone', 'Performance_Score', 'Join_date'],
      dtype='object')

In [24]:
print(df[-df['Phone'].astype(str).str.len()<10])

     St_Name  Gender       City Department    Join_Date         Phone  \
0      Pooja       M       Pune         HR  Mar 10 2024  9.876543e+09
1      Pooja  Female     Bhopal        NaN          NaN  1.234500e+04
2      Priya       F     Bhopal         IT   15/02/2024           NaN
3      Sneha  Female     Mumbai      Sales  Mar 10 2024  9.876543e+09
4      Pooja       M        NaN         IT  Mar 10 2024  1.234500e+04
...      ...     ...        ...        ...          ...           ...
4995   Rahul     NaN      Delhi    Finance  Mar 10 2024           NaN
4996   Priya     NaN    Delhi           IT  Mar 10 2024  1.234500e+04
4997   Rohit  Female    Delhi           HR          NaN           NaN
4998   Vikas    Male     Mumbai         HR          NaN  1.000000e+10
4999  Anjali  Female    Delhi        Sales          NaN           NaN

      Performance_Score Country  Discount
0                   1.0    Inia    2500.0
1                   2.0    Inia    -100.0
2                   4.0    Inia       NaN
3                   5.0    Inia    -100.0
4                   1.0    Inia    5500.0
...                 ...     ...       ...
4995                NaN    Inia    5500.0
4996                4.0    Inia    -100.0
4997                5.0    Inia    3500.0
4998                1.0    Inia    -100.0
4999                3.0    Inia    4500.0

[5000 rows x 9 columns]

In [2]:
import pandas as pd

df = pd.read_csv("Dataset-1.csv")

In [3]:
df['Phone'].astype(str).str.len(),10

(0       12
 1        7
 2        3
 3       12
 4        7
         ..
 4995     3
 4996     7
 4997     3
 4998    12
 4999     3
 Name: Phone, Length: 5000, dtype: int64,
 10)

In [4]:
df['Phone'].astype(str).str.len() < 10

0       False
1        True
2        True
3       False
4        True
        ...
4995     True
4996     True
4997     True
4998    False
4999     True
Name: Phone, Length: 5000, dtype: bool

In [5]:
import numpy as np

mask = (
    (df['Phone'].astype(str).str.len() < 10) |
    (~df['Phone'].astype(str).str.isnumeric())
)

df.loc[mask, 'Phone'] = np.nan

In [6]:
invalid_phones = df.loc[
    (df['Phone'].astype(str).str.len() < 10) |
    (~df['Phone'].astype(str).str.isnumeric())
]

print(invalid_phones)

      Customer_ID    Name    Age  Gender       City   Salary Department  \
0               1   Pooja   18.0       M       Pune  25000.0         HR
1               2   Pooja   40.0  Female     Bhopal  -1000.0        NaN
2               3   Priya   18.0       F     Bhopal      NaN         IT
3               4   Sneha   30.0  Female     Mumbai  -1000.0      Sales
4               5   Pooja   22.0       M        NaN  55000.0         IT
...           ...     ...    ...     ...        ...      ...        ...
4995         4996   Rahul   18.0     NaN      Delhi  55000.0    Finance
4996         4997   Priya  150.0     NaN    Delhi    -1000.0         IT
4997         4998   Rohit   22.0  Female    Delhi    35000.0         HR
4998         4999   Vikas  150.0    Male     Mumbai  -1000.0         HR
4999         5000  Anjali   30.0  Female    Delhi    45000.0      Sales

        Join_Date  Phone  Performance_Score
0     Mar 10 2024    NaN                1.0
1             NaN    NaN                2.0
2      15/02/2024    NaN                4.0
3     Mar 10 2024    NaN                5.0
4     Mar 10 2024    NaN                1.0
...           ...    ...                ...
4995  Mar 10 2024    NaN                NaN
4996  Mar 10 2024    NaN                4.0
4997          NaN    NaN                5.0
4998          NaN    NaN                1.0
4999          NaN    NaN                3.0

[5000 rows x 10 columns]

In [7]:
print(df['Department'].value_counts())

Department
Sales      1019
Finance     994
IT          986
HR          968
Name: count, dtype: int64

In [9]:
print(df[df['Department'].isnull()])

      Customer_ID    Name   Age  Gender       City   Salary Department  \
1               2   Pooja  40.0  Female     Bhopal  -1000.0        NaN
16             17   Rohit  35.0    Male     Mumbai  25000.0        NaN
23             24  Anjali  -5.0       F  Bengaluru  -1000.0        NaN
26             27   Priya   NaN  Female     Bhopal  -1000.0        NaN
32             33    Amit  35.0     NaN     Bhopal  -1000.0        NaN
...           ...     ...   ...     ...        ...      ...        ...
4975         4976   Rahul   NaN  Female     Mumbai  45000.0        NaN
4979         4980  Anjali  18.0       F     Bhopal      NaN        NaN
4983         4984   Rahul  35.0     NaN     Bhopal  -1000.0        NaN
4986         4987   Sneha  30.0    Male     Mumbai  55000.0        NaN
4988         4989   Rohit  25.0  Female    Delhi    55000.0        NaN

        Join_Date  Phone  Performance_Score
1             NaN    NaN                2.0
16    Mar 10 2024    NaN                5.0
23     15/02/2024    NaN                5.0
26     15/02/2024    NaN                2.0
32     2024-01-15    NaN                5.0
...           ...    ...                ...
4975   2024-01-15    NaN                4.0
4979   2024-01-15    NaN                5.0
4983   15/02/2024    NaN                NaN
4986          NaN    NaN                2.0
4988          NaN    NaN                3.0

[1033 rows x 10 columns]

In [10]:
df['Department'].fillna('Unknown',inplace=True)

C:\Users\CFRSI\AppData\Local\Temp\ipykernel_848\490358853.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].fillna('Unknown',inplace=True)

In [11]:
print(df['Salary'].max())

55000.0

In [12]:
print(df['Salary'].min())

-1000.0

In [13]:
print(df['Salary'].median())

35000.0

In [14]:
print(df['Salary'].mean())

31994.183228308288

In [15]:
Q1=df['Salary'].quantile(0.25)
Q3=df['Salary'].quantile(0.75)
IQR=Q3-Q1
outliers=df[(df['Salary']<(Q1-1.5*IQR))| (df['Salary']>(Q3+1.5*IQR))]
print(outliers)

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score]
Index: []

In [16]:
Q1=df['Age'].quantile(0.25)
Q3=df['Age'].quantile(0.75)
IQR=Q3-Q1
outliers=df[(df['Age']<(Q1-1.5*IQR))| (df['Age']>(Q3+1.5*IQR))]
print(outliers)

      Customer_ID    Name    Age  Gender       City   Salary Department  \
24             25   Priya  150.0    Male       Pune  25000.0      Sales
31             32   Sneha  150.0  Female     Bhopal  35000.0         IT
39             40  Anjali  150.0    Male    Delhi        NaN    Unknown
42             43  Anjali  150.0       F      Delhi  -1000.0         IT
51             52   Vikas  150.0  Female      Delhi  55000.0    Unknown
...           ...     ...    ...     ...        ...      ...        ...
4970         4971   Priya  150.0     NaN    Delhi    55000.0      Sales
4973         4974    Amit  150.0       M  Bengaluru      NaN    Finance
4992         4993  Anjali  150.0    Male       Pune  45000.0      Sales
4996         4997   Priya  150.0     NaN    Delhi    -1000.0         IT
4998         4999   Vikas  150.0    Male     Mumbai  -1000.0         HR

        Join_Date  Phone  Performance_Score
24            NaN    NaN                5.0
31    Mar 10 2024    NaN                5.0
39            NaN    NaN                2.0
42     2024-01-15    NaN                2.0
51     2024-01-15    NaN                1.0
...           ...    ...                ...
4970   2024-01-15    NaN                3.0
4973  Mar 10 2024    NaN                5.0
4992   2024-01-15    NaN                3.0
4996  Mar 10 2024    NaN                4.0
4998          NaN    NaN                1.0

[569 rows x 10 columns]

In [17]:
df['Age_Group']=pd.cut(df['Age'],bins=[0,18,35,50,100],labels=['Teen','Young','Adult','Senior'])

In [18]:
print(df['Age_Group'].value_counts())

Age_Group
Young     2156
Teen       610
Adult      538
Senior       0
Name: count, dtype: int64

In [26]:
print(df["City"].value_counts().head(5))

City
Mumbai       759
Pune         739
Bengaluru    716
  Delhi      712
Bhopal       685
Name: count, dtype: int64

In [2]:
import pandas as pd
df=pd.read_csv("Dataset-1.csv")
df.head()
print(df.nlargest(5,'Salary'))

    Customer_ID    Name   Age  Gender       City   Salary Department  \
4             5   Pooja  22.0       M        NaN  55000.0         IT
13           14   Rahul  -5.0    Male  Bengaluru  55000.0         IT
15           16   Priya  25.0       F     Mumbai  55000.0         IT
17           18    Amit   NaN       M  Bengaluru  55000.0      Sales
29           30  Anjali  30.0  Female     Mumbai  55000.0    Finance

      Join_Date         Phone  Performance_Score
4   Mar 10 2024  1.234500e+04                1.0
13  Mar 10 2024  9.876543e+09                3.0
15   2024-01-15  1.000000e+10                1.0
17  Mar 10 2024           NaN                NaN
29   15/02/2024  1.000000e+10                5.0

In [3]:
df=df.sort_values(by='Salary',ascending=False)

In [4]:
print(df[df['Salary']>50000])

      Customer_ID   Name    Age  Gender       City   Salary Department  \
2514         2515  Sneha   30.0       F    Delhi    55000.0      Sales
3148         3149  Rahul   30.0    Male     Bhopal  55000.0      Sales
3182         3183  Rahul   40.0     NaN        NaN  55000.0         IT
3177         3178  Priya    NaN  Female       Pune  55000.0      Sales
3176         3177  Rohit  150.0       F       Pune  55000.0         HR
...           ...    ...    ...     ...        ...      ...        ...
625           626  Sneha    NaN     NaN  Bengaluru  55000.0         HR
4008         4009  Rahul   18.0     NaN        NaN  55000.0         HR
4869         4870  Rohit   25.0       M      Delhi  55000.0         IT
4043         4044  Vikas   25.0    Male       Pune  55000.0        NaN
3842         3843  Rohit   25.0       F       Pune  55000.0        NaN

        Join_Date         Phone  Performance_Score
2514          NaN  1.000000e+10                2.0
3148   2024-01-15  1.000000e+10                1.0
3182  Mar 10 2024  1.234500e+04                3.0
3177   2024-01-15  1.000000e+10                1.0
3176   2024-01-15  9.876543e+09                NaN
...           ...           ...                ...
625           NaN  1.234500e+04                NaN
4008   2024-01-15  9.876543e+09                4.0
4869  Mar 10 2024  9.876543e+09                3.0
4043          NaN           NaN                4.0
3842   15/02/2024  9.876543e+09                3.0

[856 rows x 10 columns]

In [5]:
print(df[df["City"]=='Delhi'])

      Customer_ID    Name    Age  Gender   City   Salary Department  \
996           997   Pooja   25.0       M  Delhi  55000.0      Sales
1000         1001   Rohit   25.0       M  Delhi  55000.0        NaN
1009         1010  Anjali  150.0    Male  Delhi  55000.0    Finance
986           987   Priya   30.0    Male  Delhi  55000.0         IT
3265         3266    Amit  150.0    Male  Delhi  55000.0      Sales
...           ...     ...    ...     ...    ...      ...        ...
4796         4797   Rohit   22.0     NaN  Delhi      NaN    Finance
4876         4877   Priya   -5.0       F  Delhi      NaN         IT
4902         4903  Anjali   40.0       F  Delhi      NaN    Finance
4919         4920   Vikas   22.0  Female  Delhi      NaN         IT
4966         4967   Priya   30.0  Female  Delhi      NaN    Finance

       Join_Date         Phone  Performance_Score
996          NaN  9.876543e+09                4.0
1000  2024-01-15           NaN                3.0
1009  2024-01-15  1.234500e+04                NaN
986   15/02/2024  1.234500e+04                3.0
3265         NaN  1.000000e+10                3.0
...          ...           ...                ...
4796  15/02/2024  1.234500e+04                5.0
4876  2024-01-15           NaN                1.0
4902  15/02/2024           NaN                4.0
4919         NaN           NaN                1.0
4966  2024-01-15  1.000000e+10                3.0

[669 rows x 10 columns]

In [8]:
print(df.columns[df.isnull().all()])

Index([], dtype='object')

In [9]:
df.columns=df.columns.str.lower()

In [10]:
cleaned_df=df.copy()

In [11]:
cleaned_df.to_csv('cleaned_dataset.csv',index=False)
print("Dataset saved successfully!")

Dataset saved successfully!

In [3]:
import pandas as pd
df=pd.read_csv("Dataset-1.csv")
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0

In [4]:
df.rename(columns={"Name":"St_Name"},inplace=True)

In [5]:
df.head()

,Customer_ID,St_Name,Age,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score
0,1,Pooja,18.0,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0
1,2,Pooja,40.0,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0
2,3,Priya,18.0,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0
3,4,Sneha,30.0,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0
4,5,Pooja,22.0,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0

In [6]:
df.drop(["Customer_ID","Age"],axis=1,inplace=True)

In [19]:
df.drop(["Salary"],axis=1,inplace=True)

In [20]:
df["Country"]="Inia"

In [21]:
df.head()

,St_Name,Gender,City,Department,Join_Date,Phone,Performance_Score,Country,Discount
0,Pooja,M,Pune,HR,Mar 10 2024,9.876543e+09,1.0,Inia,2500.0
1,Pooja,Female,Bhopal,NaN,NaN,1.234500e+04,2.0,Inia,-100.0
2,Priya,F,Bhopal,IT,15/02/2024,NaN,4.0,Inia,NaN
3,Sneha,Female,Mumbai,Sales,Mar 10 2024,9.876543e+09,5.0,Inia,-100.0
4,Pooja,M,NaN,IT,Mar 10 2024,1.234500e+04,1.0,Inia,5500.0

In [10]:
df["Discount"]=df["Salary"]*0.1

In [11]:
df.head()

,St_Name,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score,Country,Discount
0,Pooja,M,Pune,25000.0,HR,Mar 10 2024,9.876543e+09,1.0,Inia,2500.0
1,Pooja,Female,Bhopal,-1000.0,NaN,NaN,1.234500e+04,2.0,Inia,-100.0
2,Priya,F,Bhopal,NaN,IT,15/02/2024,NaN,4.0,Inia,NaN
3,Sneha,Female,Mumbai,-1000.0,Sales,Mar 10 2024,9.876543e+09,5.0,Inia,-100.0
4,Pooja,M,NaN,55000.0,IT,Mar 10 2024,1.234500e+04,1.0,Inia,5500.0

In [12]:
df[df["City"]=="Delhi"]

,St_Name,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score,Country,Discount
10,Anjali,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,4.0,Inia,2500.0
21,Priya,NaN,Delhi,35000.0,Finance,2024-01-15,1.000000e+10,NaN,Inia,3500.0
33,Sneha,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,3.0,Inia,2500.0
42,Anjali,F,Delhi,-1000.0,IT,2024-01-15,1.000000e+10,2.0,Inia,-100.0
45,Anjali,M,Delhi,NaN,NaN,NaN,1.234500e+04,2.0,Inia,NaN
...,...,...,...,...,...,...,...,...,...,...
4955,Priya,NaN,Delhi,45000.0,NaN,NaN,NaN,3.0,Inia,4500.0
4966,Priya,Female,Delhi,NaN,Finance,2024-01-15,1.000000e+10,3.0,Inia,NaN
4978,Rahul,M,Delhi,-1000.0,Sales,15/02/2024,NaN,1.0,Inia,-100.0
4980,Rahul,M,Delhi,35000.0,HR,NaN,1.000000e+10,NaN,Inia,3500.0
4995,Rahul,NaN,Delhi,55000.0,Finance,Mar 10 2024,NaN,NaN,Inia,5500.0

In [13]:
df[(df["City"]=="Delhi") & (df["Department"]=="IT")]

,St_Name,Gender,City,Salary,Department,Join_Date,Phone,Performance_Score,Country,Discount
10,Anjali,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,4.0,Inia,2500.0
33,Sneha,Female,Delhi,25000.0,IT,2024-01-15,9.876543e+09,3.0,Inia,2500.0
42,Anjali,F,Delhi,-1000.0,IT,2024-01-15,1.000000e+10,2.0,Inia,-100.0
118,Amit,Male,Delhi,55000.0,IT,NaN,NaN,4.0,Inia,5500.0
154,Rahul,Female,Delhi,NaN,IT,NaN,9.876543e+09,4.0,Inia,NaN
...,...,...,...,...,...,...,...,...,...,...
4869,Rohit,M,Delhi,55000.0,IT,Mar 10 2024,9.876543e+09,3.0,Inia,5500.0
4876,Priya,F,Delhi,NaN,IT,2024-01-15,NaN,1.0,Inia,NaN
4892,Vikas,Female,Delhi,45000.0,IT,Mar 10 2024,1.234500e+04,1.0,Inia,4500.0
4896,Pooja,F,Delhi,55000.0,IT,NaN,9.876543e+09,2.0,Inia,5500.0
4919,Vikas,Female,Delhi,NaN,IT,NaN,NaN,1.0,Inia,NaN

In [15]:
df[(df["Salary"]<2500) & (df["Salary"]>6000)]

Empty DataFrame
Columns: [St_Name, Gender, City, Salary, Department, Join_Date, Phone, Performance_Score, Country, Discount]
Index: []

In [16]:
df["Department"].isin(["IT","Sales"])

0       False
1       False
2        True
3        True
4        True
        ...
4995    False
4996     True
4997    False
4998    False
4999     True
Name: Department, Length: 5000, dtype: bool